// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://mdjawxmakyscokgvdejv.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im1kamF3eG1ha3lzY29rZ3ZkZWp2Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTM0NDA1MzUsImV4cCI6MjA2OTAxNjUzNX0.E8aJaY7fr7HayPMpmrMH0YhX-GysLzTQg68hz1oI38M";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});